---
- hosts: all
  gather_facts: yes

  vars_files:
    - vars/default.config.yml

  pre_tasks:
    - name: Include playbook configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
    - name: Install system packages
      import_tasks: tasks/systempkgs.yml
      tags: ['system']

    - name: Install Docker
      import_tasks: tasks/docker.yml
      tags: ['docker']

    - name: Install kubectl
      import_tasks: tasks/kubectl.yml
      tags: ['kubectl']